model_type: 6
input_nc: 3
patch_size: 256

#0 - 24GB, 1 - 32GB, 2 - 10 - 12GB, 3 - 8GB
batch_size: [48, 64, 32, 16] #amount of images to accumulate before backprop
load_size: [48, 64, 32, 16] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
use_tanh: True
augment_key: "none"
use_cbam: False
use_involution: False

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 15
max_epochs: 20

dataset_version: "v02_fcity"
dataset_repeats: 5




