model_type: 7
input_nc: 3
patch_size: 256

#batch size for each workstation
batch_size: [12, 16, 12, 4] #amount of images to accumulate before backprop
load_size: [12, 16, 12, 4] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 6
weight_decay: 0.0
dropout_rate: 0.0
use_tanh: True
augment_key: "none"

g_lr: 0.0002
d_lr: 0.0002
min_epochs: 15
max_epochs: 20

dataset_version: "v01_fcity"
dataset_repeats: 5




