model_type: 4 #1 = vanilla cycle gan, 2 = u-net, 3 = ffa-net, #4 = cycle-gan with inv
input_nc: 3
patch_size: 64

#0 - COARE, 1 - CCS Cloud, 2 - 2080Ti, 3 - 3090
batch_size: [32, 16, 4, 8] #amount of images to accumulate before backprop
load_size: [32, 16, 4, 8] #amount of images to load in GPU. load_size <= batch_size

num_blocks: 2
weight_decay: 0.0
dropout_rate: 0.0
use_tanh: True
augment_key: "none"
use_cbam: False

g_lr: 0.0002
d_lr: 0.0005
min_epochs: 15
max_epochs: 20

dataset_version: "v01_fcity"
dataset_repeats: 5





